CREATE TABLE IF NOT EXISTS shop_type (
    id BIGINT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    sort INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shop (
    id BIGINT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    type_id BIGINT NOT NULL,
    address VARCHAR(255) NOT NULL,
    avg_price INT NOT NULL,
    phone VARCHAR(32),
    longitude DOUBLE NOT NULL,
    latitude DOUBLE NOT NULL,
    coordinate_system VARCHAR(16) NOT NULL DEFAULT 'BD-09',
    district VARCHAR(32),
    anchor_place_id VARCHAR(64),
    anchor_place_name VARCHAR(128),
    data_nature VARCHAR(32) NOT NULL DEFAULT 'synthetic_seed',
    source VARCHAR(32) NOT NULL DEFAULT 'seed',
    source_entity_id VARCHAR(128),
    original_name VARCHAR(128),
    original_address VARCHAR(255),
    original_longitude DOUBLE,
    original_latitude DOUBLE,
    localization_version VARCHAR(32),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review (
    id VARCHAR(64) PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    owner_user_id VARCHAR(36),
    content TEXT NOT NULL,
    tags VARCHAR(255) NOT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'seed',
    language VARCHAR(16) NOT NULL DEFAULT 'zh',
    content_zh TEXT,
    translation_status VARCHAR(32) NOT NULL DEFAULT 'not_required',
    source_review_id VARCHAR(128),
    source_user_id VARCHAR(128),
    stars DOUBLE,
    source_shop_name VARCHAR(128),
    evidence_scope VARCHAR(96),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_review_shop_id ON review(shop_id);
CREATE INDEX IF NOT EXISTS idx_review_owner_user_id ON review(owner_user_id);
CREATE TABLE IF NOT EXISTS user_behavior (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    shop_id BIGINT NOT NULL,
    behavior_type VARCHAR(32) NOT NULL,
    score DOUBLE,
    source VARCHAR(32) NOT NULL,
    source_user_id VARCHAR(128),
    source_review_id VARCHAR(128),
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_behavior_user_id ON user_behavior(user_id);
CREATE INDEX IF NOT EXISTS idx_user_behavior_shop_id ON user_behavior(shop_id);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    source_item_id VARCHAR(128) NOT NULL,
    title VARCHAR(512) NOT NULL,
    brand VARCHAR(128) NOT NULL,
    seller VARCHAR(255) NOT NULL,
    category_l1 VARCHAR(128) NOT NULL,
    category_l2 VARCHAR(128) NOT NULL,
    category_l3 VARCHAR(128) NOT NULL,
    snapshot_price_minor BIGINT,
    currency VARCHAR(16),
    price_status VARCHAR(32) NOT NULL,
    lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    entity_version BIGINT NOT NULL DEFAULT 1,
    attribute_text CLOB,
    data_nature VARCHAR(64) NOT NULL,
    dataset_revision VARCHAR(128) NOT NULL,
    source_license VARCHAR(64) NOT NULL,
    provenance_url VARCHAR(512) NOT NULL,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_source_item UNIQUE (source, source_item_id)
);

CREATE INDEX IF NOT EXISTS idx_product_category_l3 ON product(category_l3);
CREATE INDEX IF NOT EXISTS idx_product_brand ON product(brand);
CREATE INDEX IF NOT EXISTS idx_product_price ON product(price_status, snapshot_price_minor);
CREATE INDEX IF NOT EXISTS idx_product_search_lifecycle ON product(lifecycle_status, entity_version);

CREATE TABLE IF NOT EXISTS product_attribute (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    attribute_key VARCHAR(64) NOT NULL,
    value_type VARCHAR(16) NOT NULL,
    raw_value VARCHAR(512) NOT NULL,
    normalized_text VARCHAR(255),
    normalized_number DECIMAL(18, 4),
    normalized_boolean BOOLEAN,
    unit VARCHAR(32),
    evidence_field VARCHAR(64) NOT NULL,
    extraction_method VARCHAR(64) NOT NULL,
    confidence DECIMAL(5, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_attribute UNIQUE (product_id, attribute_key)
);

CREATE INDEX IF NOT EXISTS idx_product_attribute_product ON product_attribute(product_id);

CREATE TABLE IF NOT EXISTS user_account (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    token_version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_role (
    user_id VARCHAR(36) NOT NULL,
    role_name VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_name)
);

CREATE TABLE IF NOT EXISTS auth_session_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    token_jti VARCHAR(36),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(32) NOT NULL,
    item_id BIGINT NOT NULL,
    total_quantity INT NOT NULL,
    available_quantity INT NOT NULL,
    reserved_quantity INT NOT NULL DEFAULT 0,
    sold_quantity INT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_item UNIQUE (item_type, item_id)
);

CREATE TABLE IF NOT EXISTS inventory_reservation (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL UNIQUE,
    stock_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS coupon_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    threshold_minor BIGINT NOT NULL DEFAULT 0,
    discount_minor BIGINT NOT NULL,
    total_quantity INT NOT NULL,
    claimed_quantity INT NOT NULL DEFAULT 0,
    valid_from TIMESTAMP NOT NULL,
    valid_until TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_coupon (
    id VARCHAR(36) PRIMARY KEY,
    template_id BIGINT NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    order_id VARCHAR(36),
    claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_coupon_template UNIQUE (template_id, user_id)
);

CREATE TABLE IF NOT EXISTS customer_order (
    id VARCHAR(36) PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_minor BIGINT NOT NULL,
    discount_minor BIGINT NOT NULL DEFAULT 0,
    payable_minor BIGINT NOT NULL,
    currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
    user_coupon_id VARCHAR(36),
    expires_at TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_customer_order_idempotency UNIQUE (user_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    item_id BIGINT NOT NULL,
    title_snapshot VARCHAR(512) NOT NULL,
    unit_price_minor BIGINT NOT NULL,
    quantity INT NOT NULL,
    subtotal_minor BIGINT NOT NULL,
    evidence_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_record (
    id VARCHAR(36) PRIMARY KEY,
    payment_no VARCHAR(32) NOT NULL UNIQUE,
    order_id VARCHAR(36) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
    provider_trade_no VARCHAR(128),
    paid_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(32) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    payment_no VARCHAR(32) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payment_notification UNIQUE (provider, event_id)
);

CREATE TABLE IF NOT EXISTS refund_record (
    id VARCHAR(36) PRIMARY KEY,
    refund_no VARCHAR(32) NOT NULL UNIQUE,
    payment_id VARCHAR(36) NOT NULL,
    order_id VARCHAR(36) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    amount_minor BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider_refund_no VARCHAR(128),
    refunded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id VARCHAR(36) PRIMARY KEY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_json CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lock_owner VARCHAR(64),
    locked_at TIMESTAMP,
    published_at TIMESTAMP,
    last_error VARCHAR(1000),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_search_projection_cursor (
    product_id BIGINT PRIMARY KEY,
    entity_version BIGINT NOT NULL,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    operation VARCHAR(16) NOT NULL,
    indexed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_name VARCHAR(128) NOT NULL,
    event_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 1,
    last_error VARCHAR(1000),
    claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inbox_consumer_event UNIQUE (consumer_name, event_id)
);

CREATE TABLE IF NOT EXISTS dead_letter_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    event_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_json CLOB NOT NULL,
    attempts INT NOT NULL,
    last_error VARCHAR(1000) NOT NULL,
    failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_dead_letter_source_event UNIQUE (source, event_id)
);

CREATE TABLE IF NOT EXISTS flash_sale_campaign (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(32) NOT NULL,
    item_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    sale_price_minor BIGINT NOT NULL,
    total_stock INT NOT NULL,
    available_stock INT NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flash_sale_order (
    id VARCHAR(36) PRIMARY KEY,
    campaign_id BIGINT NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_PAYMENT',
    amount_minor BIGINT NOT NULL,
    stream_message_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_flash_sale_campaign_user UNIQUE (campaign_id, user_id),
    CONSTRAINT uk_flash_sale_stream_message UNIQUE (stream_message_id)
);
