CREATE TABLE IF NOT EXISTS shop_type (
    id BIGINT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    sort INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shop (
    id BIGINT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    type_id BIGINT NOT NULL,
    address VARCHAR(255) NOT NULL,
    avg_price INT NOT NULL,
    phone VARCHAR(32),
    longitude DOUBLE NOT NULL,
    latitude DOUBLE NOT NULL,
    coordinate_system VARCHAR(16) NOT NULL DEFAULT 'BD-09',
    district VARCHAR(32),
    anchor_place_id VARCHAR(64),
    anchor_place_name VARCHAR(128),
    data_nature VARCHAR(32) NOT NULL DEFAULT 'synthetic_seed',
    source VARCHAR(32) NOT NULL DEFAULT 'seed',
    source_entity_id VARCHAR(128),
    original_name VARCHAR(128),
    original_address VARCHAR(255),
    original_longitude DOUBLE,
    original_latitude DOUBLE,
    localization_version VARCHAR(32),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review (
    id VARCHAR(64) PRIMARY KEY,
    shop_id BIGINT NOT NULL,
    owner_user_id VARCHAR(36),
    content TEXT NOT NULL,
    tags VARCHAR(255) NOT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'seed',
    language VARCHAR(16) NOT NULL DEFAULT 'zh',
    content_zh TEXT,
    translation_status VARCHAR(32) NOT NULL DEFAULT 'not_required',
    source_review_id VARCHAR(128),
    source_user_id VARCHAR(128),
    stars DOUBLE,
    source_shop_name VARCHAR(128),
    evidence_scope VARCHAR(96),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_review_shop_id ON review(shop_id);
CREATE INDEX IF NOT EXISTS idx_review_owner_user_id ON review(owner_user_id);
CREATE TABLE IF NOT EXISTS user_behavior (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    shop_id BIGINT NOT NULL,
    behavior_type VARCHAR(32) NOT NULL,
    score DOUBLE,
    source VARCHAR(32) NOT NULL,
    source_user_id VARCHAR(128),
    source_review_id VARCHAR(128),
    occurred_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_behavior_user_id ON user_behavior(user_id);
CREATE INDEX IF NOT EXISTS idx_user_behavior_shop_id ON user_behavior(shop_id);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    source_item_id VARCHAR(128) NOT NULL,
    title VARCHAR(512) NOT NULL,
    brand VARCHAR(128) NOT NULL,
    seller VARCHAR(255) NOT NULL,
    category_l1 VARCHAR(128) NOT NULL,
    category_l2 VARCHAR(128) NOT NULL,
    category_l3 VARCHAR(128) NOT NULL,
    snapshot_price_minor BIGINT,
    currency VARCHAR(16),
    price_status VARCHAR(32) NOT NULL,
    lifecycle_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    entity_version BIGINT NOT NULL DEFAULT 1,
    attribute_text CLOB,
    data_nature VARCHAR(64) NOT NULL,
    dataset_revision VARCHAR(128) NOT NULL,
    source_license VARCHAR(64) NOT NULL,
    provenance_url VARCHAR(512) NOT NULL,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_source_item UNIQUE (source, source_item_id)
);

CREATE INDEX IF NOT EXISTS idx_product_category_l3 ON product(category_l3);
CREATE INDEX IF NOT EXISTS idx_product_brand ON product(brand);
CREATE INDEX IF NOT EXISTS idx_product_price ON product(price_status, snapshot_price_minor);
CREATE INDEX IF NOT EXISTS idx_product_search_lifecycle ON product(lifecycle_status, entity_version);

CREATE TABLE IF NOT EXISTS product_attribute (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    attribute_key VARCHAR(64) NOT NULL,
    value_type VARCHAR(16) NOT NULL,
    raw_value VARCHAR(512) NOT NULL,
    normalized_text VARCHAR(255),
    normalized_number DECIMAL(18, 4),
    normalized_boolean BOOLEAN,
    unit VARCHAR(32),
    evidence_field VARCHAR(64) NOT NULL,
    extraction_method VARCHAR(64) NOT NULL,
    confidence DECIMAL(5, 4) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_attribute UNIQUE (product_id, attribute_key)
);

CREATE INDEX IF NOT EXISTS idx_product_attribute_product ON product_attribute(product_id);

CREATE TABLE IF NOT EXISTS user_account (
    id VARCHAR(36) PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    token_version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_role (
    user_id VARCHAR(36) NOT NULL,
    role_name VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_name)
);

CREATE TABLE IF NOT EXISTS auth_session_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    token_jti VARCHAR(36),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(32) NOT NULL,
    item_id BIGINT NOT NULL,
    total_quantity INT NOT NULL,
    available_quantity INT NOT NULL,
    reserved_quantity INT NOT NULL DEFAULT 0,
    sold_quantity INT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_item UNIQUE (item_type, item_id)
);

CREATE TABLE IF NOT EXISTS inventory_reservation (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    stock_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    refunded_quantity INT NOT NULL DEFAULT 0,
    returned_quantity INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_reservation_order_stock UNIQUE(order_id,stock_id),
    CONSTRAINT ck_inventory_return_quantity CHECK(returned_quantity>=0 AND returned_quantity+refunded_quantity<=quantity)
);

CREATE TABLE IF NOT EXISTS inventory_return_receipt (
    command_id VARCHAR(128) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    item_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    disposition VARCHAR(32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK(quantity>0),
    FOREIGN KEY(stock_id) REFERENCES inventory_stock(id)
);

CREATE TABLE IF NOT EXISTS coupon_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    threshold_minor BIGINT NOT NULL DEFAULT 0,
    discount_minor BIGINT NOT NULL,
    total_quantity INT NOT NULL,
    claimed_quantity INT NOT NULL DEFAULT 0,
    valid_from TIMESTAMP NOT NULL,
    valid_until TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_coupon (
    id VARCHAR(36) PRIMARY KEY,
    template_id BIGINT NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    order_id VARCHAR(36),
    claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_user_coupon_template UNIQUE (template_id, user_id)
);

CREATE TABLE IF NOT EXISTS customer_order (
    id VARCHAR(36) PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_minor BIGINT NOT NULL,
    discount_minor BIGINT NOT NULL DEFAULT 0,
    payable_minor BIGINT NOT NULL,
    currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
    user_coupon_id VARCHAR(36),
    expires_at TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_customer_order_idempotency UNIQUE (user_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    item_id BIGINT NOT NULL,
    title_snapshot VARCHAR(512) NOT NULL,
    unit_price_minor BIGINT NOT NULL,
    quantity INT NOT NULL,
    subtotal_minor BIGINT NOT NULL,
    evidence_json CLOB,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_record (
    id VARCHAR(36) PRIMARY KEY,
    payment_no VARCHAR(32) NOT NULL UNIQUE,
    order_id VARCHAR(36) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
    provider_trade_no VARCHAR(128),
    paid_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(32) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    payment_no VARCHAR(32) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payment_notification UNIQUE (provider, event_id)
);

CREATE TABLE IF NOT EXISTS refund_record (
    id VARCHAR(36) PRIMARY KEY,
    refund_no VARCHAR(32) NOT NULL UNIQUE,
    payment_id VARCHAR(36) NOT NULL,
    order_id VARCHAR(36) NOT NULL UNIQUE,
    user_id VARCHAR(36) NOT NULL,
    amount_minor BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider_refund_no VARCHAR(128),
    refunded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id VARCHAR(36) PRIMARY KEY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_json CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lock_owner VARCHAR(64),
    locked_at TIMESTAMP,
    published_at TIMESTAMP,
    last_error VARCHAR(1000),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_search_projection_cursor (
    product_id BIGINT PRIMARY KEY,
    entity_version BIGINT NOT NULL,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    operation VARCHAR(16) NOT NULL,
    indexed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_name VARCHAR(128) NOT NULL,
    event_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 1,
    last_error VARCHAR(1000),
    claimed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inbox_consumer_event UNIQUE (consumer_name, event_id)
);

CREATE TABLE IF NOT EXISTS dead_letter_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    event_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    payload_json CLOB NOT NULL,
    attempts INT NOT NULL,
    last_error VARCHAR(1000) NOT NULL,
    failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_dead_letter_source_event UNIQUE (source, event_id)
);

CREATE TABLE IF NOT EXISTS flash_sale_campaign (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type VARCHAR(32) NOT NULL,
    item_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    sale_price_minor BIGINT NOT NULL,
    total_stock INT NOT NULL,
    available_stock INT NOT NULL,
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flash_sale_order (
    id VARCHAR(36) PRIMARY KEY,
    campaign_id BIGINT NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_PAYMENT',
    amount_minor BIGINT NOT NULL,
    stream_message_id VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_flash_sale_campaign_user UNIQUE (campaign_id, user_id),
    CONSTRAINT uk_flash_sale_stream_message UNIQUE (stream_message_id)
);

CREATE TABLE IF NOT EXISTS fulfillment_task (
    order_id VARCHAR(36) PRIMARY KEY,
    request_key VARCHAR(96) NOT NULL UNIQUE,
    command_json TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    fence BIGINT NOT NULL DEFAULT 0,
    owner VARCHAR(64),
    lease_until TIMESTAMP(6) NULL,
    next_attempt_at TIMESTAMP(6) NULL,
    tracking_no VARCHAR(128),
    receipt_json TEXT,
    last_error VARCHAR(1000),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_fulfillment_dispatch (status, next_attempt_at, lease_until),
    CONSTRAINT fk_fulfillment_order FOREIGN KEY (order_id) REFERENCES customer_order(id)
);

CREATE TABLE IF NOT EXISTS fulfillment_attempt (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    order_id VARCHAR(36) NOT NULL,
    fence BIGINT NOT NULL,
    outcome VARCHAR(32) NOT NULL,
    detail VARCHAR(1000),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_fulfillment_attempt_order (order_id, id),
    CONSTRAINT fk_fulfillment_attempt_order FOREIGN KEY (order_id) REFERENCES customer_order(id)
);
CREATE TABLE IF NOT EXISTS order_line_allocation (
    order_id VARCHAR(36) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    item_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    subtotal_minor BIGINT NOT NULL,
    discount_minor BIGINT NOT NULL,
    paid_minor BIGINT NOT NULL,
    refunded_quantity INT NOT NULL DEFAULT 0,
    refunded_minor BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY(order_id,item_id),
    CONSTRAINT fk_line_allocation_order FOREIGN KEY(order_id) REFERENCES customer_order(id),
    CONSTRAINT fk_line_allocation_stock FOREIGN KEY(stock_id) REFERENCES inventory_stock(id),
    CONSTRAINT ck_line_allocation CHECK(quantity>0 AND refunded_quantity>=0 AND refunded_quantity<=quantity
        AND subtotal_minor>=0 AND discount_minor>=0 AND paid_minor>=0
        AND subtotal_minor=discount_minor+paid_minor AND refunded_minor>=0 AND refunded_minor<=paid_minor)
);

CREATE TABLE IF NOT EXISTS fulfillment_command_version (
    order_id VARCHAR(36) NOT NULL,
    revision BIGINT NOT NULL,
    request_key VARCHAR(96) NOT NULL UNIQUE,
    command_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(order_id,revision),
    CONSTRAINT fk_fulfillment_command_order FOREIGN KEY(order_id) REFERENCES customer_order(id)
);

CREATE TABLE IF NOT EXISTS partial_refund (
    id VARCHAR(36) PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    payment_id VARCHAR(36) NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(16) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    provider_refund_no VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    refunded_at TIMESTAMP NULL,
    CONSTRAINT uk_partial_refund_key UNIQUE(order_id,idempotency_key),
    CONSTRAINT fk_partial_refund_order FOREIGN KEY(order_id) REFERENCES customer_order(id),
    CONSTRAINT fk_partial_refund_payment FOREIGN KEY(payment_id) REFERENCES payment_record(id),
    CONSTRAINT ck_partial_refund_amount CHECK(amount_minor>=0)
);
CREATE INDEX IF NOT EXISTS idx_partial_refund_status ON partial_refund(order_id,status);

CREATE TABLE IF NOT EXISTS partial_refund_item (
    refund_id VARCHAR(36) NOT NULL,
    item_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    amount_minor BIGINT NOT NULL,
    PRIMARY KEY(refund_id,item_id),
    CONSTRAINT fk_partial_refund_item FOREIGN KEY(refund_id) REFERENCES partial_refund(id),
    CONSTRAINT ck_partial_refund_item CHECK(quantity>0 AND amount_minor>=0)
);

CREATE TABLE IF NOT EXISTS local_refund_receipt (
    refund_id VARCHAR(36) PRIMARY KEY,
    provider_refund_no VARCHAR(128) NOT NULL UNIQUE,
    payment_id VARCHAR(36) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_local_refund_receipt FOREIGN KEY(refund_id) REFERENCES partial_refund(id)
);

-- Accepted flash-sale requests outlive the Redis notification stream.
CREATE TABLE IF NOT EXISTS flash_sale_request (
    id VARCHAR(36) PRIMARY KEY,
    campaign_id BIGINT NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    amount_minor BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    completed_order_id VARCHAR(36),
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_flash_request_buyer UNIQUE (campaign_id, user_id),
    CHECK (attempts >= 0)
);

-- Serializes source-authoritative review projection snapshots, including deletions.
CREATE TABLE IF NOT EXISTS review_projection_head (
    review_id VARCHAR(64) PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product_favorite (
    user_id VARCHAR(64) NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(user_id, product_id),
    FOREIGN KEY(product_id) REFERENCES product(id)
);
CREATE TABLE IF NOT EXISTS cache_invalidation_outbox (
 id VARCHAR(36) PRIMARY KEY, entity_type VARCHAR(16) NOT NULL, entity_id BIGINT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, published_at TIMESTAMP NULL,
 next_attempt_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, attempts INT DEFAULT 0,last_error VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS external_catalog_identity (
 product_id BIGINT PRIMARY KEY, raw_sha BINARY(32) NOT NULL, source_line BIGINT NOT NULL,
 source_revision CHAR(64) NOT NULL, import_version VARCHAR(128) NOT NULL,
 preserved_existing BOOLEAN NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS catalog_version_member (
 catalog_version VARCHAR(128) NOT NULL, product_id BIGINT NOT NULL,
 PRIMARY KEY(catalog_version,product_id)
);

-- New support writes stay feature-gated until their adapters and recovery are verified.
CREATE TABLE IF NOT EXISTS support_case (
 id VARCHAR(36) PRIMARY KEY,
 order_id VARCHAR(36) NOT NULL,
 user_id VARCHAR(36) NOT NULL,
 item_id BIGINT NOT NULL,
 quantity INT NOT NULL,
 original_type VARCHAR(32) NOT NULL,
 current_type VARCHAR(32) NOT NULL,
 phase VARCHAR(40) NOT NULL,
 amount_minor BIGINT NOT NULL,
 currency VARCHAR(16) NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 specification_json TEXT NULL,
 policy_version VARCHAR(64) NOT NULL,
 idempotency_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT uk_support_case_key UNIQUE(order_id,idempotency_key),
 CONSTRAINT fk_support_case_order FOREIGN KEY(order_id) REFERENCES customer_order(id),
 CONSTRAINT ck_support_case_values CHECK(quantity>0 AND amount_minor>=0 AND version>=0)
);
CREATE INDEX IF NOT EXISTS idx_support_case_owner ON support_case(user_id,created_at,id);
CREATE TABLE IF NOT EXISTS support_order_claim (
 order_id VARCHAR(36) PRIMARY KEY,
 case_id VARCHAR(36) NOT NULL UNIQUE,
 quantity INT NOT NULL,
 amount_minor BIGINT NOT NULL,
 CONSTRAINT fk_support_claim_case FOREIGN KEY(case_id) REFERENCES support_case(id),
 CONSTRAINT ck_support_claim_values CHECK(quantity>0 AND amount_minor>=0)
);
CREATE TABLE IF NOT EXISTS support_preview (
 id VARCHAR(36) PRIMARY KEY,
 order_id VARCHAR(36) NOT NULL,
 user_id VARCHAR(36) NOT NULL,
 request_json TEXT NOT NULL,
 facts_hash CHAR(64) NOT NULL,
 amount_minor BIGINT NOT NULL,
 expires_at TIMESTAMP(6) NOT NULL,
 case_id VARCHAR(36) NULL,
 CONSTRAINT fk_support_preview_order FOREIGN KEY(order_id) REFERENCES customer_order(id),
 CONSTRAINT fk_support_preview_case FOREIGN KEY(case_id) REFERENCES support_case(id)
);
CREATE TABLE IF NOT EXISTS support_event (
 id VARCHAR(36) PRIMARY KEY,
 case_id VARCHAR(36) NOT NULL,
 event_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 actor VARCHAR(128) NOT NULL,
 event_type VARCHAR(48) NOT NULL,
 from_phase VARCHAR(40) NULL,
 to_phase VARCHAR(40) NOT NULL,
 evidence_json TEXT NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT uk_support_event_key UNIQUE(case_id,event_key),
 CONSTRAINT fk_support_event_case FOREIGN KEY(case_id) REFERENCES support_case(id)
);
CREATE INDEX IF NOT EXISTS idx_support_event_case ON support_event(case_id,created_at,id);
CREATE TABLE IF NOT EXISTS support_sale_specification (
 product_id BIGINT PRIMARY KEY,
 code VARCHAR(128) NOT NULL,
 label VARCHAR(512) NOT NULL,
 version BIGINT NOT NULL,
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 CHECK(version>0)
);

CREATE TABLE IF NOT EXISTS support_receipt (
 id VARCHAR(36) PRIMARY KEY,
 case_id VARCHAR(36) NOT NULL,
 receipt_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 event_type VARCHAR(48) NOT NULL,
 expected_version BIGINT NOT NULL,
 actor VARCHAR(128) NOT NULL,
 payload_json TEXT NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 attempts INT NOT NULL DEFAULT 0,
 next_attempt_at TIMESTAMP(6) NULL,
 last_error VARCHAR(512) NULL,
 created_at TIMESTAMP(6) NOT NULL,
 applied_at TIMESTAMP(6) NULL,
 CONSTRAINT uk_support_receipt_key UNIQUE(case_id,receipt_key),
 CONSTRAINT fk_support_receipt_case FOREIGN KEY(case_id) REFERENCES support_case(id)
);
CREATE INDEX IF NOT EXISTS idx_support_receipt_pending ON support_receipt(status,created_at);
CREATE TABLE IF NOT EXISTS support_return (
 case_id VARCHAR(36) PRIMARY KEY,
 tracking_no VARCHAR(128) NOT NULL,
 item_id BIGINT NOT NULL,
 requested_quantity INT NOT NULL,
 received_quantity INT NULL,
 sellable BOOLEAN NULL,
 receipt_id VARCHAR(36) NULL,
 inspection_receipt_id VARCHAR(36) NULL,
 CONSTRAINT fk_support_return_case FOREIGN KEY(case_id) REFERENCES support_case(id)
);
CREATE TABLE IF NOT EXISTS support_refund_command (
 case_id VARCHAR(36) PRIMARY KEY,
 payment_id VARCHAR(36) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 amount_minor BIGINT NOT NULL,
 currency VARCHAR(16) NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 provider_receipt_id VARCHAR(36) NULL,
 created_at TIMESTAMP(6) NOT NULL,
 completed_at TIMESTAMP(6) NULL,
 CONSTRAINT fk_support_refund_case FOREIGN KEY(case_id) REFERENCES support_case(id),
 CONSTRAINT fk_support_refund_payment FOREIGN KEY(payment_id) REFERENCES payment_record(id),
 CHECK(amount_minor>=0)
);
CREATE TABLE IF NOT EXISTS support_stock_effect (
 effect_id VARCHAR(64) PRIMARY KEY,
 case_id VARCHAR(36) NOT NULL,
 order_id VARCHAR(36) NOT NULL,
 item_id BIGINT NOT NULL,
 quantity INT NOT NULL,
 kind VARCHAR(32) NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 receipt_id VARCHAR(128) NULL,
 attempts INT NOT NULL DEFAULT 0,
 last_error VARCHAR(512) NULL,
 created_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_support_stock_case FOREIGN KEY(case_id) REFERENCES support_case(id),
 CHECK(quantity>0 AND attempts>=0)
);
CREATE TABLE IF NOT EXISTS support_conversion_preview (
 id VARCHAR(36) PRIMARY KEY,
 case_id VARCHAR(36) NOT NULL,
 user_id VARCHAR(36) NOT NULL,
 expected_version BIGINT NOT NULL,
 amount_minor BIGINT NOT NULL,
 expires_at TIMESTAMP(6) NOT NULL,
 confirmed_key VARCHAR(128) NULL,
 CONSTRAINT fk_conversion_case FOREIGN KEY(case_id) REFERENCES support_case(id)
);
CREATE TABLE IF NOT EXISTS support_replacement (
 id VARCHAR(36) PRIMARY KEY,
 case_id VARCHAR(36) NOT NULL,
 case_version BIGINT NOT NULL,
 item_id BIGINT NOT NULL,
 quantity INT NOT NULL,
 specification TEXT NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 reserve_until TIMESTAMP(6) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT uk_replacement_attempt UNIQUE(case_id,case_version),
 CONSTRAINT fk_replacement_case FOREIGN KEY(case_id) REFERENCES support_case(id),
 CHECK(quantity>0)
);
ALTER TABLE support_replacement ADD COLUMN IF NOT EXISTS tracking_no VARCHAR(128) NULL;
ALTER TABLE support_replacement ADD COLUMN IF NOT EXISTS dispatch_receipt_id VARCHAR(36) NULL;
ALTER TABLE support_replacement ADD COLUMN IF NOT EXISTS received_receipt_id VARCHAR(36) NULL;
ALTER TABLE support_case ADD COLUMN IF NOT EXISTS recovery_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE support_case ADD COLUMN IF NOT EXISTS recovery_next_at TIMESTAMP(6) NULL;
ALTER TABLE support_case ADD COLUMN IF NOT EXISTS recovery_error VARCHAR(512) NULL;
ALTER TABLE support_stock_effect ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP(6) NULL;
CREATE TABLE IF NOT EXISTS support_ticket (
 id VARCHAR(36) PRIMARY KEY,
 order_id VARCHAR(36) NOT NULL,
 user_id VARCHAR(36) NOT NULL,
 case_id VARCHAR(36) NULL,
 category VARCHAR(40) NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
 summary VARCHAR(1000) NOT NULL,
 create_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT uk_ticket_create UNIQUE(order_id,create_key),
 CONSTRAINT fk_ticket_order FOREIGN KEY(order_id) REFERENCES customer_order(id),
 CONSTRAINT fk_ticket_case FOREIGN KEY(case_id) REFERENCES support_case(id)
);
CREATE INDEX IF NOT EXISTS idx_ticket_owner ON support_ticket(user_id,created_at,id);
CREATE TABLE IF NOT EXISTS support_scenario_clock (
 order_id VARCHAR(36) PRIMARY KEY,
 virtual_now TIMESTAMP(6) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0,
 actor VARCHAR(128) NOT NULL,
 CONSTRAINT fk_scenario_clock_order FOREIGN KEY(order_id) REFERENCES customer_order(id)
);
CREATE TABLE IF NOT EXISTS support_clock_event (
 order_id VARCHAR(36) NOT NULL,
 event_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 actor VARCHAR(128) NOT NULL,
 from_time TIMESTAMP(6) NOT NULL,
 to_time TIMESTAMP(6) NOT NULL,
 PRIMARY KEY(order_id,event_key),
 CONSTRAINT fk_clock_event_order FOREIGN KEY(order_id) REFERENCES customer_order(id)
);
CREATE TABLE IF NOT EXISTS support_order_receipt (
 id VARCHAR(36) PRIMARY KEY,
 order_id VARCHAR(36) NOT NULL,
 event_type VARCHAR(24) NOT NULL,
 receipt_key VARCHAR(128) NOT NULL,
 actor VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 claim_json TEXT NOT NULL,
 payload_json TEXT NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 created_at TIMESTAMP(6) NOT NULL,
 applied_at TIMESTAMP(6) NULL,
 CONSTRAINT uk_order_receipt_event UNIQUE(order_id,event_type),
 CONSTRAINT uk_order_receipt_key UNIQUE(order_id,receipt_key),
 CONSTRAINT fk_order_receipt_order FOREIGN KEY(order_id) REFERENCES customer_order(id)
);
CREATE TABLE IF NOT EXISTS support_ticket_event (
 id VARCHAR(36) PRIMARY KEY,
 ticket_id VARCHAR(36) NOT NULL,
 event_key VARCHAR(128) NOT NULL,
 request_hash CHAR(64) NOT NULL,
 actor VARCHAR(128) NOT NULL,
 action VARCHAR(40) NOT NULL,
 message VARCHAR(2000) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT uk_ticket_event UNIQUE(ticket_id,event_key),
 CONSTRAINT fk_ticket_event FOREIGN KEY(ticket_id) REFERENCES support_ticket(id)
);
ALTER TABLE support_order_receipt ADD COLUMN IF NOT EXISTS attempts INT NOT NULL DEFAULT 0;
ALTER TABLE support_order_receipt ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP(6) NULL;
ALTER TABLE support_order_receipt ADD COLUMN IF NOT EXISTS last_error VARCHAR(512) NULL;
