import {test,expect} from '@playwright/test'
import {readFileSync,writeFileSync} from 'node:fs'

test('real model paints, pauses, survives reload, continues and preserves commerce access',async({page,context})=>{
  test.skip(process.env.RUN_CHAT_STREAM_LIVE!=='1','Dedicated live acceptance only')
  test.setTimeout(180000)
  expect(process.env.PW_BASE_URL).toBe('http://127.0.0.1:5173')
  const out='D:/agent-experiments/chat-streaming-20260915-attempt001'
  const saved=JSON.parse(readFileSync(`${out}/session.private.json`,'utf8'))
  expect(saved.account.username).toMatch(/^stream-test-/)
  await context.addCookies(Object.entries(saved.cookies).map(([name,value])=>({name,value:String(value),url:process.env.PW_BASE_URL!,httpOnly:true,sameSite:'Lax' as const})))
  await context.setExtraHTTPHeaders({'X-Conversation-Source':'automated_test'})
  const writes:string[]=[],errors:string[]=[]
  page.on('pageerror',e=>errors.push(e.message))
  page.on('request',r=>{if(r.method()==='POST')writes.push(new URL(r.url()).pathname)})
  await page.goto('/')
  await expect(page.getByRole('table',{name:'本轮商品推荐'})).toBeVisible({timeout:30000})
  await page.getByRole('button',{name:'后端执行详情',exact:true}).click()
  await page.getByRole('checkbox',{name:'记录 Java 后端执行详情'}).check()
  await page.getByRole('button',{name:'关闭后端执行详情'}).click()
  await page.screenshot({path:`${out}/desktop-completed.png`,fullPage:true})
  const input=page.getByLabel('告诉我你想找什么')
  await input.fill('第一款手机有哪些已记录的规格？请结合现有资料详细解释，不要编造。')
  await input.press('Enter')
  const growing=page.locator('.answer-generating .markdown-copy')
  await expect(growing).not.toBeEmpty({timeout:90000})
  const first=await growing.innerText()
  await expect(page.getByRole('button',{name:'停止输出'})).toBeVisible()
  await input.fill('下一条草稿，暂不发送')
  await page.screenshot({path:`${out}/desktop-generating.png`,fullPage:true})
  await page.getByRole('button',{name:'停止输出'}).click()
  await expect(page.getByRole('button',{name:'从原检查点继续'})).toBeVisible({timeout:10000})
  const prefix=await page.locator('.chat-message.assistant').last().locator('.markdown-copy').innerText()
  expect(prefix.length).toBeGreaterThanOrEqual(first.length)
  await expect(input).toHaveValue('下一条草稿，暂不发送')
  await page.screenshot({path:`${out}/desktop-paused.png`,fullPage:true})
  await page.reload()
  await expect(page.getByRole('button',{name:'从原检查点继续'})).toBeVisible({timeout:30000})
  await expect(page.locator('.chat-message.assistant').last()).toContainText(prefix)
  await page.getByRole('button',{name:'从原检查点继续'}).click()
  await expect(page.getByRole('button',{name:'停止输出'})).toBeVisible()
  await expect(page.getByRole('button',{name:'停止输出'})).toHaveCount(0,{timeout:60000})
  const final=await page.locator('.chat-message.assistant').last().innerText()
  // Closing a Markdown list changes browser innerText paragraph spacing.
  // The provider/unit contract checks exact persisted prefix bytes separately.
  expect(final.replace(/\s/g,'')).toContain(prefix.replace(/\s/g,''))
  expect(writes.filter(p=>p.endsWith('/run'))).toHaveLength(1)
  expect(writes.filter(p=>p.endsWith('/continue'))).toHaveLength(1)
  await page.setViewportSize({width:390,height:844})
  await expect(input).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:`${out}/mobile-completed.png`,fullPage:true})
  await page.getByRole('button',{name:'切换侧栏'}).click()
  await expect(page.getByRole('navigation',{name:'历史会话列表'})).toBeVisible()
  await page.screenshot({path:`${out}/mobile-history.png`,fullPage:true})
  await page.getByRole('button',{name:'AI 导购',exact:true}).click()
  await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('button',{name:'后端执行详情',exact:true}).click()
  await page.getByRole('checkbox',{name:'记录 Java 后端执行详情'}).check()
  await page.getByRole('button',{name:'关闭后端执行详情'}).click()
  const firstCard=page.getByRole('table',{name:'本轮商品推荐'}).locator('tr[data-product-id]').first()
  await firstCard.getByRole('button',{name:/^(查看商品|已选择)$/}).click()
  await expect(page.getByRole('dialog',{name:'商品与交易'})).toBeVisible()
  await page.getByRole('button',{name:'预览订单',exact:true}).click()
  await expect(page.getByRole('button',{name:'确认下单',exact:true})).toBeEnabled()
  // Stop before confirmation: presentation tests do not need another order.
  await page.screenshot({path:`${out}/desktop-transaction.png`,fullPage:true})
  await page.getByRole('button',{name:'关闭商品与交易'}).click()
  await page.getByRole('button',{name:'后端执行详情',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'后端执行详情'})).toBeVisible()
  await page.locator('.backend-request-list').getByRole('button',{name:/预览订单/}).first().click()
  await expect(page.locator('.backend-call')).not.toHaveCount(0,{timeout:15000})
  expect(errors).toEqual([])
  expect(writes.some(p=>p.endsWith('/confirm'))).toBe(false)
  writeFileSync(`${out}/LIVE-BROWSER.json`,JSON.stringify({status:'PASS',firstVisibleChars:first.length,pausedChars:prefix.length,finalChars:final.length,writes,errors},null,2))
})
