import { test, expect } from '@playwright/test'

test.use({ extraHTTPHeaders: { 'X-Conversation-Source': 'automated_test' } })

test('real archive, readable nodes, new conversation and read-only history', async ({ page }) => {
  test.skip(process.env.RUN_LIVE_HISTORY !== '1')
  test.setTimeout(200000)
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  const query = '推荐续航好的二手手机，请给出实测依据和资料来源。'
  await page.getByLabel('告诉我你想找什么').fill(query)
  await page.getByRole('button', { name: '发送消息' }).click()
  const panel = page.getByRole('region', { name: '本轮执行控制' })
  await expect(panel).toContainText('已完成', { timeout: 150000 })
  await panel.locator('summary').click()
  await panel.getByRole('button', { name: /候选核验与资料汇总/ }).click()
  const detail = panel.getByRole('region', { name: '节点详情' })
  await expect(detail).toContainText('compare_products')
  await expect(detail).toContainText('调用规则')
  await expect(detail).toContainText('用户需求')
  await page.screenshot({ path: 'test-results/history-tool-desktop.png', fullPage: true })
  await panel.getByRole('button', { name: /执行工具/ }).first().click()
  await expect(detail).toContainText('实际工具')
  await expect(detail).not.toContainText('null')
  await page.screenshot({ path: 'test-results/history-stage-desktop.png', fullPage: true })
  await page.getByRole('button', { name: '新建对话', exact: true }).click()
  await expect(page.locator('.chat-message')).toHaveCount(0)
  await expect(page.getByLabel('告诉我你想找什么')).toBeEnabled()
  await page.reload()
  await expect(page.locator('.chat-message')).toHaveCount(0)
  await page.getByRole('button', { name: '历史对话', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '历史对话' })
  await dialog.getByRole('button', { name: new RegExp('推荐续航好的二手手机') }).click()
  await expect(dialog.locator('.history-message.user')).toContainText(query)
  await expect(dialog.locator('.history-message.assistant')).toHaveCount(1)
  await expect(dialog).toContainText('历史只读')
  await page.screenshot({ path: 'test-results/history-dialog-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/history-dialog-mobile.png', fullPage: true })
  await dialog.getByRole('button', { name: '返回当前对话' }).click()
  await expect(page.locator('.chat-message')).toHaveCount(0)
  expect(errors).toEqual([])
})
