import { test, expect } from '@playwright/test'
import { randomBytes } from 'node:crypto'

test('live unified guest guide -> login -> favorite -> order -> local payment -> owned order',async({page})=>{
  test.skip(process.env.RUN_LIVE_SHOP!=='1','Opt-in: live guide query (model call verified separately), isolated account/order, local payment only.')
  test.setTimeout(240_000)
  page.setDefaultTimeout(20_000)
  const username=`workspace-qa-${Date.now()}`, password=randomBytes(20).toString('hex')
  await page.goto('/')
  await page.getByLabel('告诉我你想找什么').fill('推荐2000元以内的二手手机')
  await expect(page.getByRole('button',{name:'发送消息'})).toBeEnabled({timeout:20000})
  await page.getByRole('button',{name:'发送消息'}).click()
  await expect(page.locator('.shop-product').first()).toBeVisible({timeout:170_000})
  await page.evaluate(() => window.scrollTo(0,0))
  await page.screenshot({path:'test-results/unified-live-guide.png',fullPage:true})
  const purchasable=page.locator('.shop-product[data-purchasable="true"]').first()
  await purchasable.getByRole('button',{name:'查看商品',exact:true}).click()
  await expect(page.getByRole('button',{name:'预览订单'})).toBeEnabled()
  await page.getByRole('button',{name:'预览订单'}).click()
  await page.getByRole('button',{name:'创建账户',exact:true}).click()
  await page.getByLabel('用户名',{exact:true}).fill(username)
  await page.getByLabel('密码',{exact:true}).fill(password)
  await page.getByLabel('确认密码').fill(password)
  await page.getByRole('button',{name:'注册并登录'}).click()
  await expect(page.locator('.account-name')).toContainText(username)
  await expect(page.locator('.shop-product').first()).toBeVisible()
  await page.locator('.shop-product.chosen .icon-button').click()
  await expect(page.locator('.shop-product.chosen .icon-button')).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'我的收藏',exact:true}).click()
  await page.getByRole('button',{name:'已选择',exact:true}).click()
  await page.getByLabel('数量',{exact:true}).fill('2')
  const previewResponse = page.waitForResponse(r=>r.url().endsWith('/workspace/preview') && r.request().method()==='POST')
  await page.getByRole('button',{name:'预览订单'}).click()
  const confirmationId = (await (await previewResponse).json()).checkout.proposal.confirmationId
  await expect(page.getByRole('button',{name:'确认下单',exact:true})).toBeEnabled()
  // Re-authenticate the same owner before confirming: a new JWT must not orphan this card.
  await page.getByRole('button',{name:'退出登录'}).click()
  await page.getByRole('button',{name:'登录 / 注册'}).click()
  await page.getByLabel('用户名',{exact:true}).fill(username)
  await page.getByLabel('密码',{exact:true}).fill(password)
  await page.getByRole('button',{name:'登录账户',exact:true}).click()
  await expect(page.getByRole('button',{name:'确认下单',exact:true})).toBeEnabled()
  await expect(page.getByRole('region',{name:'交易确认卡'})).toContainText('数量 × 2')
  let confirmationPosts = 0
  await page.route('**/api/commerce-demo/workspace/confirm',async route=>{
    confirmationPosts++
    if(confirmationPosts===1) {
      expect(route.request().postDataJSON().confirmationId).toBe(confirmationId)
      const response=await route.fetch()
      expect(response.ok()).toBe(true)
      // The server has completed; deliberately lose its response. UI must recover, not write again.
      await route.abort('failed')
    } else await route.continue()
  })
  await page.getByRole('button',{name:'确认下单',exact:true}).click()
  await expect(page.getByText('订单已创建',{exact:true})).toBeVisible({timeout:20000})
  expect(confirmationPosts).toBe(1)
  await page.getByRole('button',{name:'去支付',exact:true}).click()
  await page.getByRole('button',{name:'确认发起支付',exact:true}).click()
  await expect(page.getByRole('button',{name:'本地模拟支付成功'})).toBeEnabled({timeout:20000})
  await page.getByRole('button',{name:'本地模拟支付成功'}).click()
  await expect(page.locator('.order-card')).toHaveCount(1,{timeout:20000})
  await expect(page.locator('.status-badge')).toHaveText('已支付')
  await expect(page.locator('.order-card-footer')).toContainText('共 2 件商品')
  expect(confirmationPosts).toBe(2) // one order confirmation, one payment confirmation
  await page.screenshot({path:'test-results/unified-live-paid.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/unified-live-mobile-paid.png',fullPage:true})
  await page.reload()
  await expect(page.locator('.order-card')).toHaveCount(1)
  await page.getByRole('button',{name:'我的收藏',exact:true}).click()
  await expect(page.locator('.shop-product')).toHaveCount(1)
  await page.getByRole('button',{name:'退出登录'}).click()
  await expect(page.getByRole('button',{name:'登录查看收藏'})).toBeVisible()
  expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length])).toEqual([0,0])
  test.info().annotations.push({type:'isolated-test-account',description:username})
})
