/** Reviewed against the Java implementations, not generated from English method names.
 * These describe responsibilities and possible branches, never prove an observed success.
 * The source coverage test keeps additions to the commerce surface from silently falling back.
 */
export const learningCatalog: Record<string, readonly [string, string]> = {
  'ProductMapper.findByCatalogFilters': ['只在指定目录中筛选商品', '先限定目录版本的成员，再按关键词、分类、品牌和价格条件筛选；全量商城新增商品不会混进旧手机目录。'],
  'LocalOfferService.findProductIds': ['批量找出有本地报价的商品', '报价功能开启时，将编号去重、每 500 个一批查询本地报价表，返回有报价的编号集合；不读取具体售价，也不代表库存充足。'],
  'ProductCache.invalidateAllLocal': ['清空本实例的商品详情缓存', '移除当前 Java 进程里的全部商品缓存条目；不会删除 Redis、商品记录或订单。'],
  'ShopCache.invalidateAllLocal': ['清空本实例的店铺缓存', '移除当前 Java 进程里的全部店铺缓存条目；不会删除 Redis 或数据库中的店铺。'],
  'ProductMapper.findPublishedByIdAfter': ['分页读取指定已发布目录', '只读取指定目录版本的成员，按商品编号继续向后分页；用于限制旧搜索同步范围，不会把新增全量商品自动加入旧手机目录。'],
  'ProductMapper.findByIds': ['批量读取指定商品资料', '按传入的商品编号清单查询商品表，返回实际存在的商品记录；不为缺失编号创建商品。'],
  'ProductMapper.findCommerceFactsByIds': ['批量核对候选商品的交易资料', '按商品编号清单关联商品与库存，读取快照价格、价格状态、上下架状态和库存版本等字段；不查本地报价、不扣库存、不创建订单。'],
  'ProductCache.getDetail': ['先查本机缓存，再查 Redis', '先查看 Caffeine；已有商品或空值条目就返回。本机未命中才读取 Redis，把读到的商品或空值填回本机。Redis 缺失、内容损坏或读取异常会返回未命中，由商品服务决定是否查数据库。'],
  'ProductCache.putDetail': ['把查到的商品填回两级缓存', '先把商品详情序列化后写入 Redis，并设置带随机浮动的过期时间，再放入 Caffeine。写缓存异常只记录日志，因此方法返回不能单独证明两级都写入成功。'],
  'ProductCache.putEmpty': ['缓存“这个商品不存在”的结果', '在 Redis 写入短期空值，并在 Caffeine 保存空结果，减少对同一不存在商品的重复查询。它与单纯没命中缓存不同。'],
  'ProductCache.deleteDetail': ['清除商品旧缓存并通知其他实例', '先清除本机条目，再尝试删除 Redis 条目并发布失效通知。Redis 操作失败会记录日志；这个调用不能证明所有实例已经清除。'],
  'ProductCache.invalidateLocal': ['只清除本实例的商品缓存', '从当前 Java 进程的 Caffeine 中移除指定商品，不删除数据库中的商品，也不直接删除 Redis 条目。'],
  'ProductCache.tryLockDetail': ['尝试取得缓存重建资格', '用带过期时间的 Redis SET NX 协调同一商品的缓存重建。竞争失败返回空；Redis 异常时允许降级查询，因此返回令牌不一定表示真正取得了 Redis 锁。'],
  'ProductCache.unlockDetail': ['释放属于本次请求的重建锁', '通过 Lua 先核对锁内令牌，只有与本次令牌相同才删除，避免误删其他请求的锁。这里只释放重建资格，不删除商品缓存。'],
  'ProductController.list': ['接收商品筛选条件', '把关键词、品牌、分类、价格范围和数量上限交给商品服务，返回候选商品摘要。'],
  'ProductController.retrieval': ['接收检索请求并返回检索来源', '把搜索条件交给商品服务，除候选商品外还返回检索来源、召回数量及降级信息，供 Agent 判断此次检索。'],
  'ProductController.resolve': ['接收待核对的商品编号清单', '校验编号清单并交给商品服务逐个解析详情，返回实际找到的商品，不为缺失商品编造资料。'],
  'ProductService.list': ['取得符合条件的商品摘要', '调用带检索记录的查询逻辑，再取其中的商品列表；这个方法本身不下单。'],
  'ProductService.searchWithTrace': ['检索候选并核对商品事实', '有关键词且搜索组件可用时优先检索，再从数据库核对候选与硬条件；搜索未提供结果时走数据库筛选，并记录降级来源。不能仅凭搜索命中就认定可购买。'],
  'ProductService.resolve': ['去重后逐个读取商品详情', '对传入的商品编号去重，再调用详情读取逻辑，过滤没有找到的商品。这里不是一条批量 SQL 查询。'],
  'ProductFavoriteController.list': ['查看自己的商品收藏', '取当前登录用户，读取该用户的收藏商品列表，不返回其他用户的收藏。'],
  'ProductFavoriteController.add': ['把这件商品加入收藏', '先查询并确认商品存在，再为当前登录用户写入收藏关系。重复收藏不会创建重复关系。'],
  'ProductFavoriteController.remove': ['取消这件商品的收藏', '删除当前用户与此商品的收藏关系，不删除商品本身。'],
  'ProductFavoriteMapper.list': ['读取收藏对应的商品资料', '将收藏关系与商品表关联，按收藏时间倒序返回当前用户最多 200 件收藏商品。'],
  'ProductFavoriteMapper.add': ['保存用户与商品的收藏关系', '写入用户和商品编号；唯一键冲突时复用原关系，避免重复收藏。'],
  'ProductFavoriteMapper.remove': ['删除当前用户的收藏关系', '同时按用户与商品编号删除收藏，操作范围不是所有用户的收藏。'],
  'ProductAdminController.create': ['校验新增商品资料', '严格解析新增字段并校验参数，再交给商品管理服务写入；未知字段或格式错误会被拒绝。'],
  'ProductAdminController.update': ['接收商品修改与预期版本', '校验编号和修改字段，将版本条件一起交给商品管理服务，避免覆盖其他人的修改。'],
  'ProductAdminController.delete': ['接收商品下架删除请求', '把商品编号和预期版本交给管理服务，走逻辑删除而不是直接清空相关订单。'],
  'ProductAdminService.create': ['保存新商品并登记索引更新', '写入商品，核验初始在售状态与版本，再登记搜索更新事件，并安排事务提交后清除缓存。事件登记不代表搜索索引已经更新。'],
  'ProductAdminService.update': ['按版本修改商品并安排缓存失效', '校验商品在售状态、预期版本与价格字段，条件更新后核对版本递增，登记索引事件并在事务提交后清除旧缓存。'],
  'ProductAdminService.delete': ['将商品标记删除并登记索引删除', '核对商品版本后标记为已删除，确认版本递增，登记搜索删除事件并安排提交后缓存失效。保留数据库记录。'],
  'ProductMapper.insert': ['写入商品初始资料', '将商品标题、来源、分类和价格等写入商品表，初始状态为在售、版本为 1。最终保存仍取决于事务。'],
  'ProductMapper.findByIdAfter': ['按编号继续读取商品目录', '读取大于上一批末尾编号的商品，按编号升序并限制条数；用于分批遍历。'],
  'ProductMapper.findActiveByIdAfter': ['分批读取在售商品', '在编号游标之后只读取在售商品，按编号升序返回指定条数。'],
  'ProductMapper.findByLifecycleStatus': ['按上架状态读取商品', '按指定生命周期状态筛选商品并限制返回数量，不在此处判断库存。'],
  'ProductMapper.update': ['仅在版本匹配时更新商品', '只修改请求提供的字段，并递增版本；商品必须仍在售且版本匹配，否则不会命中更新。'],
  'ProductMapper.softDelete': ['按版本把商品标记为已删除', '在商品仍在售且版本匹配时改为删除状态并递增版本，不物理删除商品行。'],
  'CatalogInternalController.manifest': ['读取最新商品目录版本', '为内部索引构建返回已发布的目录清单；没有发布版本时返回失败提示。'],
  'CatalogInternalController.products': ['按指定版本分批读取目录', '要求提供目录版本，将批量大小限制在 10 到 500，再读取该版本下一批商品；版本不匹配会提示重建。'],
  'TradeCatalogInternalController.getItem': ['向交易端提供商品核验资料', '按商品类型和编号调用交易目录校验，返回名称、价格、版本及依据快照，而不是直接创建订单。'],
  'OrderController.listMine': ['接收查看我的订单请求', '将当前登录用户交给订单服务，返回此用户的订单及明细。'],
  'OrderController.page': ['接收订单翻页条件', '读取页大小、状态和游标，默认每页 20 单，再交给分页服务。不会用前端传入的用户编号替代当前登录用户。'],
  'OrderController.getByIdempotencyKey': ['接收按原请求回查订单', '将原幂等键和当前用户交给订单服务，只查询此前建单结果，不重建订单。'],
  'OrderController.get': ['接收查看指定订单的请求', '把订单编号、当前用户及特权角色标记交给订单服务核对访问权限。'],
  'OrderController.cancel': ['接收取消待支付订单的请求', '交给订单服务核对归属与状态；库存和优惠券的释放由后续业务步骤处理。'],
  'OrderController.complete': ['接收确认收货的请求', '使用当前用户身份调用订单完成逻辑，由服务核对订单归属和履约条件。'],
  'OrderService.getByIdempotencyKey': ['用原幂等键回查建单结果', '按用户和原幂等键查订单并组装明细；未查到会返回不存在，不把未查到解释为可以安全换键重下。'],
  'OrderService.listMine': ['批量组装自己的订单明细', '先查询用户订单，再每批最多 200 个订单编号读取明细，按归属装回订单，避免逐单查询明细。'],
  'OrderService.cancel': ['关闭待支付订单并释放占用', '检查订单归属；已取消则直接返回。否则条件改为取消，再释放预占库存、返还关联优惠券并登记取消事件，失败由事务回滚。'],
  'OrderService.complete': ['核验收货条件并完成订单', '检查订单归属，调用履约收货校验，再尝试把已支付订单改为已完成；不是仅凭按钮点击就确认完成。'],
  'OrderService.markPaid': ['把支付结果落实到订单与库存', '已支付订单直接返回；否则将待支付订单改为已支付，确认预占库存并登记支付后的订单事件。最终以事务结果为准。'],
  'OrderService.markRefunding': ['检查履约条件并进入退款中', '先让履约逻辑检查是否允许退款，再条件地把已支付订单改成退款中。'],
  'OrderService.markRefunded': ['完成整单退款状态变更', '将退款中的订单改为已退款，调用履约退款处理并登记订单退款事件；此处不是向真实支付渠道转账。'],
  'OrderService.expireBatch': ['关闭超时未支付的订单', '分批查询已到期的待支付订单；成功改成过期后，释放库存、返还优惠券并登记过期事件。状态已变化的订单不会按成功过期处理。'],
  'OrderService.requireOwnedOrder': ['确认订单属于当前用户', '读取订单并检查所有者，不属于当前用户时拒绝访问；这里不修改订单。'],
  'OrderMapper.findByUserId': ['读取当前用户的订单主记录', '按用户编号查询订单，并按创建时间倒序返回；商品明细需要后续另行读取。'],
  'OrderMapper.transition': ['仅在原状态匹配时推进订单', '按订单编号和预期状态条件更新目标状态与版本；匹配不到不会强行覆盖并发修改。更新执行后仍要看事务。'],
  'OrderMapper.findExpiredIds': ['找出超时待支付订单', '只读取到期且仍待支付的订单编号，按到期时间排序并限制数量，供后续关单。'],
  'InventoryController.get': ['接收查询库存的请求', '校验商品类型和编号，交给库存服务读取现有配置，不创建库存。'],
  'InventoryController.create': ['接收库存初始化请求', '管理员入口校验商品类型、编号和数量，再调用库存服务创建库存记录。'],
  'InventoryService.confirm': ['将预占库存确认为已售', '逐条检查订单预占记录，将仍处于预占中的记录改为已确认，再把预占数量转为已售；已确认记录跳过，冲突会抛出异常。'],
  'InventoryService.setRemote': ['接入独立库存服务', '应用启动时注入分布式库存客户端；这里只配置后续调用的依赖，不修改库存，也不是一次用户交易。'],
  'ProductOfferController.setRemoteInventory': ['接入库存只读接口', '应用启动时注入库存查询客户端；商品服务用它获取库存信息，不因此获得预占或释放库存的权限。'],
  'InventoryService.release': ['把未支付占用的库存放回可售', '逐条检查预占记录，将仍预占的记录改为释放或过期，再把数量放回可用库存；已经释放的记录不会重复归还。'],
  'InventoryService.restoreUnshipped': ['恢复整单未出库退款的库存', '调用方须先确认未派发。此方法把已确认预占标为退款并将已售数量放回可售；已退款则不重复恢复。'],
  'InventoryService.restoreUnshippedQuantity': ['按退款件数恢复可售库存', '核对对应库存，条件累加该订单已退数量，再减少已售、增加可用；超过已确认且未退数量会拒绝。调用方需先核验未派发。'],
  'InventoryService.createStock': ['建立商品库存记录', '插入初始总量和可用数量，再读取新记录返回。它是配置库存，不是对现实仓库盘点。'],
  'InventoryMapper.insertStock': ['保存初始库存数量', '将总量和可用数量设为配置数量，预占和已售数量设为零。'],
  'InventoryMapper.confirm': ['从预占数量转入已售数量', '只有预占数量足够才减少预占并增加已售，同时递增版本。'],
  'InventoryMapper.release': ['将预占数量归还可用数量', '条件减少预占、增加可用并递增版本；预占不足不会命中更新。'],
  'InventoryMapper.refundConfirmedReservation': ['标记整单已确认库存为已退款', '只将该订单处于已确认状态的预占记录改为退款状态，不在这条语句中增加可售数量。'],
  'InventoryMapper.restoreSold': ['减少已售数量并恢复可售数量', '只有已售数量足够才增加可用、减少已售并递增库存版本。'],
  'InventoryMapper.findReservationByOrder': ['读取订单的预占凭据', '按订单编号查询预占记录，供库存确认、释放或退款判断使用。'],
  'InventoryMapper.findReservations': ['按固定顺序读取订单全部预占', '读取该订单所有预占记录并按库存编号排序，后续逐条处理。'],
  'InventoryMapper.transitionOne': ['按原状态更新一条预占凭据', '同时匹配预占编号和预期状态，才改为目标状态，避免重复或并发操作覆盖。'],
  'InventoryMapper.refundQuantity': ['累计该商品已退款的件数', '仅处理已确认库存，且累计退款不能超过预占数量；全部退完时改为已退款，否则保留已确认状态。'],
  'InventoryMapper.transitionReservation': ['修改订单仍在预占中的记录', '只更新该订单处于预占状态的记录为指定目标状态；已确认或已释放记录不匹配。'],
  'CouponController.createTemplate': ['接收优惠券规则配置', '管理员提交门槛、优惠金额、数量和有效期，交给优惠券服务校验保存。'],
  'CouponController.claim': ['接收当前用户的领券请求', '将券模板编号和当前登录用户交给领券服务；是否领到由名额及重复领取检查决定。'],
  'CouponController.listMine': ['接收查看我的优惠券请求', '使用当前登录用户读取其持有的券及状态。'],
  'CouponService.createTemplate': ['校验有效期并建立优惠券规则', '结束时间必须晚于开始时间，随后保存模板并读取返回；此时还没有给具体用户发券。'],
  'CouponService.claim': ['扣减领券名额并为用户发券', '先条件增加已领取数量，再保存用户券；未生效、过期、领完或同用户重复领取会失败，写入由事务保护。'],
  'CouponService.listMine': ['查询用户持有的优惠券', '按用户编号读取优惠券记录，不在这里消耗优惠券。'],
  'CouponService.releaseByOrder': ['返还这张订单使用的优惠券', '将关联此订单且已使用的券恢复可用，清除订单关联与使用时间。后续是否仍符合有效期要再次校验。'],
  'CouponMapper.insertTemplate': ['保存优惠券门槛与发放数量', '写入模板名称、减免金额、门槛、有效期和总量，初始已领取数量为零。'],
  'CouponMapper.findTemplate': ['读取优惠券使用规则', '按模板编号读取门槛、减免金额、有效期、状态及已领取数量。'],
  'CouponMapper.claimQuota': ['有名额且有效时占用一个领券名额', '模板须启用、在有效期内且尚未领完，才增加已领取数量；更新不到记录表示条件未满足。'],
  'CouponMapper.insertUserCoupon': ['保存这位用户领到的券', '将用户与券模板关联，初始状态为可用；唯一约束阻止重复领取。'],
  'CouponMapper.findUserCoupon': ['读取一张用户券的归属和状态', '按用户券编号查询所属用户、模板、状态及关联订单；归属校验由上层服务继续完成。'],
  'CouponMapper.consume': ['把本人可用的券标记为已使用', '必须同时匹配券编号、当前用户和可用状态，才关联订单并记为已使用。'],
  'CouponMapper.releaseByOrder': ['解除订单与已使用券的关联', '只返还与此订单关联且已使用的券，不修改其他订单的券。'],
  'PaymentController.create': ['接收发起支付请求', '把订单编号和当前用户交给支付服务；创建支付单不等于完成付款。'],
  'PaymentController.getByOrder': ['接收支付结果回查请求', '按订单编号和当前用户查询已经存在的支付单，不重新发起支付。'],
  'PaymentController.callback': ['接收支付渠道通知', '把渠道、通知内容与签名交给支付服务核验，不能仅凭收到通知就改成支付成功。'],
  'PaymentController.simulateSuccess': ['接收本地模拟支付操作', '将支付单及当前用户交给模拟支付逻辑，仍要检查模拟器开关和支付单归属；不是实际扣款。'],
  'PaymentController.requestRefund': ['接收整单退款申请', '将订单、退款原因和当前用户交给退款逻辑；申请返回不等于退款成功。'],
  'PaymentController.simulateRefundSuccess': ['接收本地模拟整单退款', '调用模拟退款逻辑核验归属和状态，仅验证本地流程，不发生真实资金退款。'],
  'PaymentService.create': ['复用或建立订单的支付单', '先核对订单归属；已有支付单则复用。新建时要求订单待支付且未到期，以订单应付金额创建本地模拟渠道支付单。'],
  'PaymentService.getByOrderId': ['核对归属后读取支付状态', '检查订单属于当前用户，再读此订单支付单；不存在就提示不存在，不把缺少结果当成支付失败。'],
  'PaymentService.processCallback': ['核验支付通知并推进订单', '检查签名、支付渠道、事件重复及金额。成功通知才尝试更新支付单并确认订单库存；失败通知走失败状态分支，同事件不同内容会拒绝。'],
  'PaymentService.simulateSuccess': ['生成并处理本地成功支付通知', '先检查模拟器开启和支付单归属，再生成带签名的本地成功通知，复用回调处理逻辑；没有真实扣款。'],
  'PaymentService.requestRefund': ['建立整单退款申请', '核对订单归属与成功支付，拒绝购物车按数量退款与整单退款混用；复用已有退款，否则检查履约条件并保存退款中记录。'],
  'PaymentService.simulateRefundSuccess': ['在本地确认整单退款结果', '检查模拟开关、退款归属和状态，条件写入模拟成功结果，再推进订单及履约退款；重复成功不重复处理。'],
  'PaymentMapper.cartLines': ['检查订单是否有多商品分摊记录', '统计该订单的明细分摊记录，供整单退款入口判断是否应该使用按数量退款。'],
  'PaymentMapper.insertPayment': ['保存支付单与订单金额', '写入支付编号、归属、渠道、金额和初始状态；不是支付渠道的成功回执。'],
  'PaymentMapper.findById': ['按支付单编号读取支付记录', '读取支付状态、金额、渠道与关联订单，供归属核验或回调处理。'],
  'PaymentMapper.findByPaymentNo': ['按支付业务号读取支付记录', '用通知中的支付业务号查原支付单，以核对渠道和金额。'],
  'PaymentMapper.findByOrderId': ['查询订单是否已有支付单', '按订单编号读取支付记录，用于复用支付单或查询支付结果。'],
  'PaymentMapper.markSuccess': ['条件写入支付成功状态', '只有仍处于已创建状态的支付单才更新为成功，并记录渠道流水和支付时间；最终保存要看事务。'],
  'PaymentMapper.markFailed': ['条件写入支付失败状态', '只把尚处于已创建状态的支付单改为失败，不覆盖已成功的支付单。'],
  'PaymentMapper.insertNotification': ['保存支付通知的去重凭据', '记录渠道、事件编号、支付号及内容摘要，防止同一通知被重复处理。'],
  'PaymentMapper.findNotificationHash': ['核对重复通知的内容是否相同', '读取同渠道、同事件的已存摘要，供服务比较重复通知是否篡改了内容。'],
  'PaymentMapper.insertRefund': ['保存整单退款申请', '记录退款对应的支付单、订单、用户、金额和原因，后续还需要确认退款结果。'],
  'PaymentMapper.findRefundById': ['按退款编号查询整单退款', '读取退款金额、状态及渠道退款流水，供后续处理。'],
  'PaymentMapper.findRefundByOrderId': ['检查订单是否已有整单退款', '按订单编号查询退款记录，防止同一订单重复建立整单退款。'],
  'PaymentMapper.markRefundSuccess': ['条件写入整单退款成功状态', '只将处理中退款改为成功，并保存渠道退款流水；其他状态不会被直接覆盖。'],
  'PartialRefundController.create': ['接收按商品件数退款的申请', '将订单、退款商品清单、幂等键和登录用户交给退款服务，返回申请结果而非直接退款到账。'],
  'PartialRefundController.balance': ['接收查看剩余可退数量的请求', '查询此用户订单各商品的实付分摊及已退数量金额。'],
  'PartialRefundController.preview': ['接收按数量退款的试算请求', '把所选商品和件数交给退款服务计算预计金额；试算不创建退款。'],
  'PartialRefundController.byKey': ['接收按原幂等键回查退款', '使用订单、当前用户和原请求键查询已有退款记录，不另建申请。'],
  'PartialRefundController.get': ['接收查看按数量退款详情', '按退款编号交给服务核对归属，再返回退款及商品明细。'],
  'PartialRefundController.simulate': ['生成本地退款回执后进行对账', '先由独立模拟器事务保存回执，再调用退款对账；中途丢失响应时，后续仍可按持久回执回查。'],
  'PartialRefundController.reconcile': ['接收退款结果对账请求', '将退款编号和当前用户交给服务核验已持久化渠道回执；没有匹配回执不能算退款成功。'],
  'PartialRefundService.create': ['锁定订单并核算按数量退款', '核验清单与幂等键，锁定本人订单后检查支付、已退余额及其他退款；按整数分计算退款，核对确认金额并暂停派发，保存处理中退款和明细。'],
  'PartialRefundService.get': ['读取退款状态与所退商品', '查询退款并检查用户归属，再读取所退商品件数和金额，组装返回。'],
  'PartialRefundService.reconcile': ['核对回执后落实退款与库存', '锁定本人订单并核对持久回执的支付身份、币种及金额；无回执保持处理中。匹配后按库存顺序更新退款分摊、恢复未派发库存、调整履约并登记事件。'],
  'PartialRefundService.balance': ['读取订单商品的退款余额', '先验证订单属于当前用户，再读取每件商品分摊实付及已退数量金额；不等于此刻一定允许发起退款。'],
  'PartialRefundService.byKey': ['查找原请求对应的退款', '核对订单归属后按订单、用户和幂等键查退款，再读取完整明细；无记录则提示尚无回执。'],
  'PartialRefundService.quote': ['按剩余件数试算可退金额', '要求本人已支付订单，检查商品归属、重复项和剩余数量，按已分摊实付计算退款金额；不写退款或恢复库存。'],
  'FlashSaleController.listCampaigns': ['接收查看抢购活动的请求', '调用活动列表查询，返回活动资料；展示活动不代表当前仍有名额。'],
  'FlashSaleController.create': ['接收管理员新增抢购活动', '校验活动配置后交给服务建立草稿，不在这个入口直接启用抢购。'],
  'FlashSaleController.activate': ['接收管理员启用抢购活动', '将活动编号交给启用逻辑，准备 Redis 侧抢购状态并切换数据库活动状态。'],
  'FlashSaleController.purchase': ['接收当前用户的抢购请求', '交给抢购服务核验并受理；入口使用已受理响应，不表示订单已落库或已支付。'],
  'FlashSaleController.listMine': ['接收查看我的抢购订单请求', '使用当前登录用户查询已生成的抢购订单。'],
  'FlashSaleService.create': ['建立抢购活动草稿', '检查活动结束晚于开始，保存商品、活动价、名额及时间，初始状态为草稿。'],
  'FlashSaleService.activate': ['准备抢购缓存并启用草稿', '已启用则复用；草稿活动先重建 Redis 库存和购买者集合，再条件启用数据库活动。其他状态会拒绝。'],
  'FlashSaleService.purchase': ['检查活动并持久受理抢购', '先回查已受理请求，再检查开关、状态和活动时间；调用 Lua 检查重复与预扣库存，成功后保存持久受理记录。排队中不等于已创建最终订单。'],
  'FlashSaleService.listCampaigns': ['读取数据库里的抢购活动', '查询活动列表，包含各活动的状态、价格与时间，是否可抢仍在提交时核验。'],
  'FlashSaleService.listMine': ['读取用户已落库的抢购订单', '按用户读取抢购订单；这里查的是订单，不把排队受理自动当成订单。'],
  'FlashSaleRedisGateway.purchase': ['通过 Lua 检查资格并预扣名额', '把活动、用户、订单及金额交给 Redis 脚本，返回受理、售罄、重复购买或未就绪；Lua 返回受理不代表数据库订单已经保存。'],
  'FlashSaleRedisGateway.rebuild': ['重建 Redis 抢购库存与资格记录', '尝试取得重建锁，暂时移除就绪标记，重建库存和购买者等数据后恢复就绪；拿不到锁则返回，不保证本次执行了重建。'],
  'FlashSaleRedisGateway.isReady': ['检查抢购缓存是否就绪', '只检查 Redis 中活动就绪标记是否存在，不证明还有可售名额。'],
  'FlashSaleRedisGateway.compensate': ['按原预占身份尝试归还抢购名额', 'Lua 核对用户对应的预占订单，匹配且移除购买者成功才归还名额，避免补偿其他请求或重复归还。'],
  'FlashSaleOrderPersistenceService.deadLetterOrder': ['终止失败请求前检查是否已经落单', '锁定活动后查询该用户订单，已有订单就登记完成，不误补偿；确实无订单时保存死信并标记请求失败。'],
  'FlashSaleOrderPersistenceService.compensationCompleted': ['登记抢购请求已完成补偿', '更新持久受理记录的补偿状态；这一步本身不执行 Redis 库存归还。'],
  'FlashSaleMapper.insertCampaign': ['保存抢购活动草稿与初始库存', '写入活动商品、金额、起止时间和库存，可用名额初始等于总名额。'],
  'FlashSaleMapper.findCampaign': ['读取指定抢购活动', '按活动编号查询状态、时间、价格及数据库剩余名额。'],
  'FlashSaleMapper.lockCampaign': ['读取并锁定活动记录', '使用行锁协调该活动的落单与终止补偿，锁的持有范围取决于事务。'],
  'FlashSaleMapper.findActiveCampaigns': ['读取已启用的抢购活动', '按活动状态筛选已启用活动，供恢复等后续处理；不在这里判断是否仍在时间窗口内。'],
  'FlashSaleMapper.activate': ['条件启用抢购活动', '只把草稿改为启用并递增版本，状态已经变化则不会命中更新。'],
  'FlashSaleMapper.decrementDatabaseStock': ['在数据库中扣减一个抢购名额', '活动须启用且剩余名额大于零，才扣减名额并递增版本，作为落单阶段的条件保护。'],
  'FlashSaleMapper.findOrder': ['查询指定抢购订单是否已存在', '按抢购订单编号读取已落库记录，用于重复投递检查。'],
  'FlashSaleMapper.findOrderByCampaignAndUser': ['检查用户在本活动是否已有订单', '按活动与用户查询已生成的抢购订单，供一人一单检查和异常恢复。'],
  'FlashSaleMapper.findBuyerIds': ['读取活动已经落单的用户', '从该活动抢购订单中读取用户编号，供购买资格恢复使用。'],
  'FlashSaleMapper.findReservedBuyerIds': ['汇总已下单和排队中的购买者', '合并已落单用户与仍在排队的持久请求用户，重建资格时避免忽略排队占用。'],
  'FlashSaleMapper.pendingReservations': ['统计尚未落单的排队占用', '只统计仍在排队且该用户尚无对应活动订单的请求，避免与已落单库存重复计算。'],
  'FlashSaleMapper.reservations': ['读取尚未落单的预占请求', '查询仍在排队且没有对应订单的请求及用户，用于恢复原预占身份。'],
  'FlashSaleMapper.insertOrder': ['保存抢购订单', '写入订单、活动、用户、金额及通知编号；写入执行不等于所属事务已提交。'],
  'FlashSaleMapper.insertDeadLetter': ['保留抢购落单失败的原始通知', '保存失败通知、尝试次数和错误；重复记录时更新失败信息，供排查与恢复。'],
  'AuthController.register': ['接收注册请求', '校验注册参数并交给身份服务建立账户及登录凭证；讲解不展示密码或令牌。'],
  'AuthController.login': ['核验用户名和密码', '将登录参数交给身份服务检查账户可用性及密码，成功后签发登录凭证；不能从方法返回类型推断登录成功。'],
  'AuthController.refresh': ['请求轮换登录凭证', '交给身份服务验证并消耗原刷新令牌，再签发新凭证；重复使用原令牌会触发安全处理。'],
  'AuthController.logout': ['撤销当前刷新凭证会话', '交给身份服务撤销刷新令牌所属会话并记录退出；不声称立即销毁所有已签发访问令牌。'],
  'UserAccountMapper.insert': ['保存新用户账户', '写入用户编号、用户名和加密后的密码摘要等账户字段；不应在讲解中暴露这些敏感内容。'],
  'UserAccountMapper.insertRole': ['为账户保存角色', '建立用户与角色的关联，后续鉴权据此确定权限。'],
  'UserAccountMapper.findByUsername': ['按用户名查询登录账户', '读取账户状态与密码摘要供身份服务验证；查询到账户并不代表密码正确。'],
  'UserAccountMapper.findById': ['按用户编号查询账户状态', '读取账户是否启用及令牌版本等，供身份流程核验，不修改账户。'],
  'UserAccountMapper.findRoles': ['读取账户角色列表', '查询用户角色，供签发凭证等身份流程使用。'],
  'UserAccountMapper.insertAudit': ['保存登录会话审计记录', '登记注册、登录、刷新或退出等会话事件，便于追溯；不是商品购买行为。'],
  'OutboxService.appendIdempotent': ['按业务身份登记唯一待发送事件', '从幂等键生成稳定事件编号；重复写入时核对类型、业务对象及内容，一致则复用，不一致就拒绝。登记不等于消息已投递。'],
  'OutboxMapper.findDispatchableIds': ['寻找可以投递或接管的事件', '读取已到重试时间的待发送事件，以及占用已超时的处理事件，按发生顺序限制批量。'],
  'OutboxMapper.claim': ['条件取得这条事件的投递权', '只有待发送或占用已超时且已到执行时间的事件，才写入当前处理者和处理中状态。'],
  'OutboxMapper.findById': ['读取持久化事件内容', '按事件编号读取内容、类型、投递状态及重试信息。'],
  'OutboxMapper.markPublished': ['确认本处理者的事件已经投递', '必须仍由当前处理者占用，才将事件标为已发布并清除占用；已发布不等于消费端业务完成。'],
  'OutboxMapper.markFailure': ['记录投递失败和下一次处理安排', '核对处理者所有权后增加尝试次数、记录错误及下一次时间，并释放占用。目标可能是待重试或终止，取决于传入状态。'],
  'OutboxMapper.insertDeadLetter': ['保存重试耗尽的事件证据', '把原始事件内容、失败次数和错误写入死信记录，便于排查恢复，不丢弃失败内容。'],
  'OutboxMapper.countByStatus': ['统计指定状态的待投递事件', '按状态统计 Outbox 记录数量，用于观察积压或处理状态。'],
  'InboxMapper.insertClaim': ['登记消费端对事件的处理占用', '以消费者和事件身份保存处理中记录及内容摘要；处理中不是已处理成功。'],
  'InboxMapper.find': ['读取这条事件在消费端的处理状态', '按消费者和事件编号读取状态、摘要、尝试次数及错误，用于去重和恢复判断。'],
  'InboxMapper.reclaim': ['接管失败或超时的消费任务', '仅对失败记录或占用超时的处理中记录重新占用并增加尝试次数，不抢占仍有效的处理中任务。'],
  'InboxMapper.markProcessed': ['将消费记录确认为已处理', '只把对应消费者仍处于处理中的事件改为已处理，防止把其他状态直接算作完成。'],
  'InboxMapper.markFailed': ['记录本次消费处理失败', '把处理中事件改为失败并保存错误，供后续重试判断。'],
  'InboxMapper.markDead': ['将失败消费记录转为终止状态', '只将失败记录改为死信状态；原始事件证据由另一条写入保存。'],
  'InboxMapper.insertDeadLetter': ['持久保存无法完成的消费事件', '写入事件原始内容、来源、尝试次数和错误，后续可据此排查或重放。'],
  'InboxMapper.countByStatus': ['统计消费端处理状态', '统计指定状态的消费记录数量，用于观察处理中、失败或已完成情况。'],
  'ProductSearchEventService.productUpserted': ['登记商品搜索索引更新事件', '在商品业务事务内，按商品编号和版本登记幂等更新事件，等待异步更新搜索索引。'],
  'ProductSearchEventService.productDeleted': ['登记商品搜索索引删除事件', '在商品业务事务内登记对应版本的幂等删除事件；不是此刻已经删除搜索索引。'],
  'UserBehaviorController.createBehavior': ['接收商户相关的用户行为', '普通用户使用登录身份，服务角色可指定用户，再交给服务核验商户并记录行为；它不是自动保存所有聊天消息。'],
  'UserBehaviorController.listUserBehaviors': ['接收行为历史查询条件', '读取用户编号和数量上限交给行为服务，返回已记录的商户相关行为。'],
  'UserBehaviorService.createBehavior': ['核验商户并保存用户行为', '先确认商户存在，再保存行为类型、评分、来源及发生时间，读取新记录返回。'],
  'UserBehaviorService.listUserBehaviors': ['按数量上限读取用户行为', '规范化用户编号和查询条数，默认 20 条、最多 100 条，查询已登记行为并转为响应。'],
  'UserBehaviorMapper.insert': ['写入一条商户行为记录', '保存用户、商户、行为类型、来源与发生时间，不等同于创建交易订单。'],
  'UserBehaviorMapper.findById': ['读取刚保存的行为详情', '按行为编号读取用户、商户及行为内容，供返回或核对使用。'],
  'UserBehaviorMapper.findByUserId': ['读取用户最近的行为', '按用户查询并按发生时间和创建时间倒序排列，限制返回数量。'],
  'UserBehaviorMapper.findRecent': ['读取最近登记的行为样本', '按时间倒序读取限制数量的行为记录，不限定某个用户。'],
  'HealthController.health': ['返回 Java 服务存活响应', '返回服务名称和运行标记，仅说明此接口可响应，不是对全部数据库、Redis 和消息队列的健康检查。'],
  'ShopController.listShops': ['接收商户分类和名称筛选', '把分类与名称条件交给商户服务，返回匹配的商户摘要。'],
  'ShopController.listNearbyShops': ['接收附近商户查询位置', '把经纬度、分类、搜索半径和数量上限交给商户服务，返回附近候选及距离。'],
  'ShopController.getShop': ['接收查看商户详情的请求', '按编号调用商户服务；找到返回详情，未找到返回商户不存在。'],
  'ShopController.updateShop': ['接收商户资料修改', '校验地址、人均价格等修改参数，交给商户服务保存并处理缓存。'],
  'ShopService.listShops': ['搜索商户并核对分类', '有名称且配置搜索组件时先搜索，再读取商户核对分类；搜索未提供结果时改用数据库条件查询。'],
  'ShopService.listNearbyShops': ['按距离筛选附近商户', '先读取商户资料，有分类和地理缓存时尝试 Redis GEO，必要时重建；仍无可用结果时在 Java 中算距离，按半径筛选并排序。不是全程不查数据库。'],
  'ShopService.getShop': ['优先从缓存读取商户详情', '命中商品以外的商户缓存就返回；未命中时协调重建并再次检查缓存，必要时查询数据库。缓存空值表示曾查无此商户。'],
  'ShopService.updateShop': ['保存商户修改并安排缓存清除', '更新商户资料，配置了 Outbox 时登记更新事件，事务提交后清除详情缓存，再读取修改后的商户返回。'],
  'ShopCache.getDetail': ['先查本机，再查 Redis 商户缓存', 'Caffeine 有条目则直接返回；否则读取 Redis，将商品以外的商户详情或空结果填回本机。读取失败或内容损坏返回未命中。'],
  'ShopCache.putDetail': ['缓存查到的商户详情', '将商户详情写入带过期时间的 Redis，再填入 Caffeine。异常仅记录日志，返回不保证缓存写入成功。'],
  'ShopCache.putEmptyDetail': ['短期记住商户不存在的结果', '在 Redis 与本机保存空结果，减少对同一不存在商户的重复查询；不会删除商户表。'],
  'ShopCache.deleteDetail': ['清除本机和 Redis 商户缓存', '先删除本机商户条目，再尝试删除 Redis。此方法没有发布跨实例广播，不应与商品缓存的广播逻辑混为一谈。'],
  'ShopCache.invalidateLocal': ['只清除当前实例的商户缓存', '从本 Java 进程的 Caffeine 移除指定商户，不修改数据库或 Redis。'],
  'ShopCache.tryLockDetail': ['尝试协调商户缓存重建', '通过带过期时间的 Redis SET NX 取得重建资格；竞争失败返回空，Redis 异常则放行降级查询，不能一概认为拿到了锁。'],
  'ShopCache.unlockDetail': ['按令牌释放商户重建锁', 'Lua 先比较本次持有的令牌，匹配时才删除锁，避免误删其他请求的锁。'],
  'ShopGeoCache.rebuildTypeIndex': ['重建某类商户的位置索引', '删除该分类旧的 Redis GEO 键，再按传入商户逐个加入坐标；异常会记录日志，返回不证明重建完整。'],
  'ShopGeoCache.findNearby': ['在 Redis 中搜索附近商户', '以经纬度为中心查询指定分类地理索引，按距离升序返回限量候选。异常会返回空列表，因此空结果不一定表示现实中没有附近商户。'],
  'ShopMapper.findAll': ['读取商户目录', '按编号读取商户表资料，供列表、评论关联或推荐等上层功能使用。'],
  'ShopMapper.findByTypeId': ['读取指定分类的商户', '按商户分类筛选数据库记录，并按商户编号排序。'],
  'ShopMapper.findByFilters': ['按分类与名称查询商户', '由 SQL 构造器按传入条件筛选商户，返回目录资料。'],
  'ShopMapper.findById': ['读取指定商户资料', '按商户编号查询名称、地址、人均价格和位置等字段；不是查询普通商品库存。'],
  'ShopMapper.updateDetails': ['修改商户地址与消费资料', '按商户编号更新地址、人均价格、电话和更新时间，返回受影响记录数。'],
  'ShopTypeController.listShopTypes': ['接收商户分类查询', '将可选关键词交给分类服务，返回匹配的商户分类。'],
  'ShopTypeController.getShopType': ['接收查看指定商户分类', '按分类编号查询，存在则返回分类，不存在返回相应提示。'],
  'ShopTypeService.listShopTypes': ['按名称筛选商户分类', '先读全部分类；有关键词时在 Java 中按名称包含关系筛选，没有关键词则全部返回。'],
  'ShopTypeService.getShopType': ['读取一项商户分类', '按分类编号查询并转换为分类响应，不读取该分类下所有商户。'],
  'ShopTypeMapper.findAll': ['按显示顺序读取商户分类', '从商户分类表读取编号、名称及排序值，并按排序值排列。'],
  'ShopTypeMapper.findById': ['按编号查询商户分类', '只读取此分类的名称和排序资料，不查询商户或订单。'],
  'ReviewController.listReviews': ['接收商户评论查询', '将可选商户编号交给评论服务，读取评论及关联商户信息。'],
  'ReviewController.createReview': ['接收当前用户发表的商户评论', '校验内容和标签，使用登录用户作为作者交给评论服务；这是商户评论入口，不是已购商品评价认证。'],
  'ReviewController.updateReview': ['接收商户评论修改', '将评论编号、内容、当前用户及管理员标记交给服务检查权限后修改。'],
  'ReviewController.deleteReview': ['接收删除商户评论的请求', '将评论编号和当前用户权限交给服务，不能只凭前端传来的评论编号直接删除。'],
  'ReviewService.listReviews': ['组合评论与商户名称', '按可选商户条件读取评论，再读取商户目录并按编号关联，返回评论内容、来源、翻译状态及标签。'],
  'ReviewService.createReview': ['保存商户评论并安排检索同步', '确认商户存在，清理内容与重复标签，保存评论并读回；按配置直接同步向量检索或登记 Outbox 事件。'],
  'ReviewService.updateReview': ['核对作者权限后修改评论', '要求本人评论或管理员权限，再更新内容与标签、读取结果并安排检索同步。'],
  'ReviewService.deleteReview': ['核对权限并删除评论', '读取评论并验证作者或管理员权限，删除数据库记录后按配置直接同步删除或登记待投递删除事件。'],
  'ReviewMapper.findAll': ['读取商户评论记录', '按编号读取评论表中的内容、标签及来源等资料，未按单一商户筛选。'],
  'ReviewMapper.findByShopId': ['读取某个商户的评论', '按商户编号筛选评论，返回内容与来源等字段。'],
  'ReviewMapper.insert': ['保存用户发表的中文评论', '写入评论、商户和作者关系以及标签，来源设为用户、语言设为中文。'],
  'ReviewMapper.findById': ['读取一条评论及作者信息', '按评论编号查询，供上层核验归属、修改或组装响应。'],
  'ReviewMapper.update': ['更新评论正文与标签', '按评论编号修改内容、标签及更新时间；权限检查在调用它之前完成。'],
  'ReviewMapper.deleteById': ['删除指定评论记录', '按评论编号删除数据库记录；检索索引删除由上层另行安排。'],
  'ShopRecommendationController.recommendShops': ['接收个性化商户推荐请求', '把用户编号、推荐数量及可选位置范围交给推荐服务。'],
  'ShopRecommendationService.recommendShops': ['结合行为相似度与热度推荐商户', '读取用户历史和近期行为，组合 ItemCF 相似商户、热门商户及分类补充，排除已接触商户；有位置时筛选距离，再按得分等规则排序。不是大模型凭空生成商户。'],
  'ProductSearchProjectionCursorMapper.findVersionForUpdate': ['锁定商品已处理的索引版本', '读取并锁定该商品搜索投影的版本记录，供上层判断消息是否过旧。'],
  'ProductSearchProjectionCursorMapper.advance': ['只向前推进搜索投影版本', '保存已处理版本与事件；已有记录时只接受更高版本对应的信息，不让旧事件把版本倒退。'],
  'ShoppingMemoryController.write': ['拒绝缺少可信授权的旧版记忆写入', '旧接口会先检查字段和格式，随后返回授权不可用；当前不会调用旧写入服务，不能把这个入口讲成已保存偏好。'],
  'ShoppingMemoryController.issueV2Consent': ['接收明确偏好的授权申请', '严格校验第二版请求字段，使用当前登录用户申请一次短期授权；此时还未写入偏好。'],
  'ShoppingMemoryController.writeV2': ['接收带授权的偏好修改命令', '校验第二版命令格式后，将当前用户、命令及授权编号交给服务处理，不能由请求自行指定记忆所有者。'],
  'ShoppingMemoryController.issueV3Consent': ['接收目录约束偏好的授权申请', '校验第三版偏好及命令字段，用登录身份向服务申请授权，等待后续正式写入。'],
  'ShoppingMemoryController.validateV3Candidate': ['接收待确认的偏好候选', '校验候选格式，再到服务核对其目录版本、属性和值；校验通过不等于已记住。'],
  'ShoppingMemoryController.writeV3': ['接收目录约束的记忆命令', '严格解析第三版命令并使用登录身份交给服务，后续仍要核对授权、幂等和历史版本。'],
  'ShoppingMemoryController.projection': ['接收读取旧版有效偏好的请求', '使用登录用户读取可用于推荐的第一版偏好视图，不返回完整聊天记录。'],
  'ShoppingMemoryController.projectionV2': ['接收读取分类偏好的请求', '使用登录用户读取第二版偏好视图，后续会核验归属、有效性及版本链。'],
  'ShoppingMemoryController.projectionV3': ['接收读取目录约束偏好的请求', '使用登录身份读取第三版偏好视图，只返回经服务校验的有效条目。'],
  'ShoppingMemoryService.write': ['按旧版协议追加偏好版本', '服务方法校验摘要、操作与前序版本，记录同意凭据、偏好、审计及事件，提交后失效缓存。当前旧 HTTP 写入入口会拒绝调用它，方法存在不代表对外启用。'],
  'ShoppingMemoryService.issueV2Consent': ['为一次明确偏好操作签发短期授权', '校验偏好及操作，生成绑定用户、命令和内容摘要的五分钟授权；这里只建立授权，不保存偏好内容为有效记忆。'],
  'ShoppingMemoryService.writeV2': ['消费授权并幂等保存偏好版本', '先查询命令账本复用已完成结果，再条件消费匹配授权、核对前序版本，保存新偏好和审计、推进视图版本并完成命令；提交后清除缓存。'],
  'ShoppingMemoryService.projection': ['提取有效偏好条目列表', '调用第一版偏好视图逻辑，取其中的条目返回，不查询全部对话。'],
  'ShoppingMemoryService.projectionEnvelope': ['核对数据库版本后读取偏好缓存', '先读取数据库视图版本，没有版本就返回初始空视图；存在时才尝试匹配版本的缓存，未命中再查有效偏好，并检查响应大小。'],
  'ShoppingMemoryService.projectionV2Envelope': ['用权威偏好视图校验缓存', '读取数据库版本并重新核验候选与完整版本链，限制条数及大小。只有缓存与权威视图完全一致才复用，否则清除并重写缓存。'],
  'ShoppingMemoryV3Service.issueConsent': ['为目录约束偏好签发授权', '校验操作、偏好结构及需要的目录取值，保存绑定用户和命令摘要的短期授权，不在此时应用偏好。'],
  'ShoppingMemoryV3Service.validateCandidate': ['核对偏好取值并返回可读名称', '检查用户身份格式和候选结构，确认目录中存在对应有效取值并读取显示名称；不写入偏好。'],
  'ShoppingMemoryV3Service.write': ['带授权与版本保护地保存目录偏好', '核对目录约束、命令账本和一次性授权，再检查前序版本；允许合规地重新记住已撤销的偏好，追加可审计新版本、更新视图版本并登记完成结果。'],
  'ShoppingMemoryV3Service.projection': ['筛出仍有效且版本链完整的偏好', '从数据库读取视图版本、有效候选及各自历史链，核对身份和链条后最多选八条，并检查输出大小；不把所有历史偏好直接交给 Agent。'],
  'MemoryMapper.latestForUpdate': ['锁定同一偏好的最新旧版记录', '按用户、记忆类别和语义键找最高版本并加行锁，用于检查前序版本。'],
  'MemoryMapper.consumeConsent': ['保存旧版同意凭据的使用记录', '写入用户、同意事件和摘要，利用唯一约束阻止同一凭据被重复消耗；不等于服务器签发过可信授权。'],
  'MemoryMapper.insert': ['追加一条旧版偏好版本', '保存偏好值、版本、状态、到期时间及前序关联，不覆盖原有历史记录。'],
  'MemoryMapper.audit': ['登记这次偏好变更的审计信息', '保存操作、对应记忆与授权摘要，作为可追溯记录；所属事务回滚时不能当成已完成。'],
  'MemoryMapper.advanceProjectionHead': ['递增用户偏好视图版本', '首次建立版本，已有版本则加一，让后续读取能识别旧缓存。'],
  'MemoryMapper.projectionRevision': ['读取用户偏好的权威版本号', '从数据库读取当前视图版本，决定缓存是否具备可核对的版本依据。'],
  'MemoryMapper.projection': ['读取最新且未过期的旧版偏好', '仅选择此用户有效、未过期且没有更高版本的购物偏好，最多返回八条。'],
  'MemoryMapper.projectionV2Candidates': ['筛选明确来源的分类偏好候选', '读取本人、指定商品分类、明确用户来源的有效未过期偏好，排除已有后续版本的记录；最多读 65 条供上层检查数量上限。'],
  'MemoryMapper.projectionV2Chain': ['读取分类偏好的完整历史版本链', '按用户、分类、对象和语义键取全部版本，供服务核对前后关联，不能仅看最后一条。'],
  'MemoryMapper.latestV2ForUpdate': ['锁定待修改分类偏好的最新版本', '按用户、商品分类、对象和语义键查询最新记录并加锁，防止并发修改跳过前序检查。'],
  'MemoryMapper.issueV2Consent': ['持久保存一次性偏好授权', '保存授权所属用户、命令、动作、内容摘要及过期时间，供后续写入条件核验；第二版和第三版共用此表。'],
  'MemoryMapper.reserveV2Command': ['为偏好命令建立去重账本', '尝试插入处理中命令，重复键不再插入；是否能复用必须继续核对已存摘要和结果。'],
  'MemoryMapper.v2CommandResultForUpdate': ['锁定并读取原偏好命令结果', '按用户和命令编号读取账本并加锁，区分已完成、仍处理中或参数冲突。'],
  'MemoryMapper.consumeV2Consent': ['仅消耗与本次命令完全匹配的授权', '同时匹配用户、命令、动作和摘要，且授权未使用、未过期，才标记已消费；更新不到记录就不能授权写入。'],
  'MemoryMapper.insertV2': ['保存带商品分类的偏好新版本', '追加用户明确偏好的分类、对象、来源、值和状态，保留前序版本与摘要。'],
  'MemoryMapper.completeV2Command': ['给偏好命令保存可重放的结果', '只有同用户同命令、摘要匹配且仍处理中时，才记录应用完成及记忆编号、版本与状态。'],
  'MemoryMapper.catalogValueExists': ['检查偏好值是否属于有效目录', '按目录版本、分类、属性和值查有效记录数，避免使用目录里不存在的偏好取值。'],
  'MemoryMapper.catalogValueLabel': ['读取已登记偏好值的显示名称', '对匹配目录版本和属性的有效取值读取名称，前端无需自行猜测其含义。'],
  'MemoryMapper.latestV3ForUpdate': ['锁定目录约束偏好的最新版本', '限定第三版、用户、分类、对象和属性，读取最高版本并加锁，供更新或重新启用检查。'],
  'MemoryMapper.insertV3': ['追加目录约束的偏好记录', '保存偏好倾向、目录版本、规范化属性值、来源及前序关联，保留可核验的版本历史。'],
  'MemoryMapper.projectionV3Candidates': ['读取用户确认的有效目录偏好', '只选择本人、用户确认来源、有效未过期且没有更新版本的第三版偏好，供服务进一步核验。'],
  'MemoryMapper.projectionV3Chain': ['读取目录偏好的历史版本链', '按用户、分类、对象和属性读取第三版完整版本序列，用于检查链条是否连续、状态是否允许继续使用。'],
}
